# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q0QmzIUVcab_UcvvgroIXO1TUujbaDs2
"""

### Libraries and packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/titanic-training-data.csv")

df.sample(10)

df.shape

df.info()

df.isnull().sum()

df.describe(include="all")

## univariate analysis
sns.countplot(x="Pclass",data=df)

sns.countplot(x="Embarked",data=df)

sns.countplot(x="Sex",data=df)

df.hist(figsize=(10,15))
plt.show()

sns.boxplot(x="Age",data=df)

sns.countplot(x="Sex",hue="Survived",data=df)

sns.countplot(x="Pclass",hue="Survived",data=df)

sns.boxplot(x="Pclass",y="Age",data=df)

sns.catplot(x="Pclass",y="Age",data=df,kind="violin")

sns.pairplot(df)

corr=df.corr()
corr

sns.heatmap(corr,annot=True)



